### ISSUE TITLE
Elastic Container Registry (ECR) - docker tag command is not working

### ISSUE THREAD

**Issue by Arvind644** [localstack/docs#858] opened 2023-10-14 11:03 UTC
In the ECR docs, in the push the docker image to the registry section, docker pull command is not working while using this tag command : `docker tag localstack-ecr-image localhost:4510/localstack-ecr-repository` .

Solution : 
Using this docker tag command is working fine : 
`docker tag localstack-ecr-image localhost.localstack.cloud:4510/localstack-ecr-repository`

**Comment by joe4dev** [comment] 2023-10-18 10:29
Thank you @Arvind644 for pointing this out 👍 Fixed in the linked PR.

(duplicate of https://github.com/localstack/docs/issues/844)

**Closed** 2023-10-18 15:34 UTC
